name: Running Test

on:
  push:
    branches: master
  pull_request:
    branches: master
  schedule:
    - cron: '0 02 * * *'
    
env:
  GOOGLE_URL: ${{ secrets.GOOGLE_URL }}
  RALALI_WEB_URL: ${{ secrets.RALALI_WEB_URL }}

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: npm cache
      uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/lock.json') }}
    - run: yarn install
    - run: npm run test-webui -- -e TAGS=''
    - run: npm run reports
    - name: Reporting
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: Reports
        path: reports
